name: Hello Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          echo "JQ: $(jq --version)"
          echo "curl: $(curl --version)"

      - name: Show System Information
        run: |
          echo "Running on $(uname -s) $(uname -r)"
          echo "Current User: $(whoami)"
          echo "System Architecture: $(uname -m)"

      - name: Run a simple script
        run: echo "Hello, World!"
